export const regions = [
    // Example regions for Spain
    { country: 'es', value: 'AN', text: 'Andalucía' },
    { country: 'es', value: 'AR', text: 'Aragón' },
    { country: 'es', value: 'AS', text: 'Asturias' },
    { country: 'es', value: 'CN', text: 'Canarias' },
    { country: 'es', value: 'CB', text: 'Cantabria' },
    { country: 'es', value: 'CM', text: 'Castilla-La Mancha' },
    { country: 'es', value: 'CL', text: 'Castilla y León' },
    { country: 'es', value: 'CT', text: 'Cataluña' },
    { country: 'es', value: 'EX', text: 'Extremadura' },
    { country: 'es', value: 'GA', text: 'Galicia' },
    { country: 'es', value: 'MD', text: 'Madrid' },
    { country: 'es', value: 'MC', text: 'Murcia' },
    { country: 'es', value: 'NC', text: 'Navarra' },
    { country: 'es', value: 'PV', text: 'País Vasco' },
    { country: 'es', value: 'RI', text: 'La Rioja' },
    { country: 'es', value: 'VC', text: 'Comunidad Valenciana' },
    { country: 'es', value: 'B', text: 'Barcelona' },
    { country: 'es', value: 'GI', text: 'province of Girona' },
    // Example regions for France
    { country: 'fr', value: 'ARA', text: 'Auvergne-Rhône-Alpes' },
    { country: 'fr', value: 'BFC', text: 'Bourgogne-Franche-Comté' },
    { country: 'fr', value: 'BRE', text: 'Bretagne' },
    { country: 'fr', value: 'CVL', text: 'Centre-Val de Loire' },
    { country: 'fr', value: 'GES', text: 'Grand Est' },
    { country: 'fr', value: 'HDF', text: 'Hauts-de-France' },
    { country: 'fr', value: 'IDF', text: 'Île-de-France' },
    { country: 'fr', value: 'NOR', text: 'Normandie' },
    { country: 'fr', value: 'NAQ', text: 'Nouvelle-Aquitaine' },
    { country: 'fr', value: 'OCC', text: 'Occitanie' },
    { country: 'fr', value: 'PDL', text: 'Pays de la Loire' },
    { country: 'fr', value: 'PAC', text: 'Provence-Alpes-Côte d\'Azur' }]